Fix error in lambda CLI due to 'Orchestrated' field in API response.
The 'Orchestrated' field was removed in https://gerrit.wikimedia.org/r/c/mediawiki/extensions/WikiLambda/+/803929.

Before:

```
$ ./src/lambda.js --evaluate 'true'
/home/aassaf/code/wikipedia/lambda-cli/src/evaluate.js:31
          JSON.parse(body).query.wikilambda_function_call.Orchestrated.data
                                                                      ^

TypeError: Cannot read property 'data' of undefined
    at IncomingMessage.<anonymous> (/home/aassaf/code/wikipedia/lambda-cli/src/evaluate.js:31:71)
    at IncomingMessage.emit (node:events:381:22)
    at IncomingMessage.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

After:

```
$ ./src/lambda.js --evaluate 'true'
true
```

BUG: T308771